### ISSUE TITLE
可以在文档里写一下使用说明吗

### ISSUE THREAD

**Issue by XinghaiGe** [openschoolcn/zfn_api#13]
可以在文档里写一下使用说明吗，不太会用，谢谢。

**Comment by XinghaiGe** [comment]
我用的是账号密码登录,貌似登录成功了，但是返回了一个“无功能权限”的界面。命令行输出如下：

C:\Users\XinghaiGe\Desktop\zfn_api-main>python zfn_api.py
Traceback (most recent call last):
  File "C:\Users\XinghaiGe\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 910, in 
json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XinghaiGe\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XinghaiGe\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XinghaiGe\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode       
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 13)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XinghaiGe\Desktop\zfn_api-main\zfn_api.py", line 208, in get_info
    info = req_info.json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XinghaiGe\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 917, in 
json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value]





<!doctype html>
<html>
<head>
        <title>错误提示</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/zftal-ui-v5-1.0.2/assets/css/zftal-ui.css?ver=28814644" />       
        <link rel="stylesheet" type="text/css" href="/zftal-ui-v5-1.0.2/assets/css/error.css?ver=28814644" />
        <script type="text/javascript">
        //表示是独立错误页面
        if(!document.getElementById("yhgnPage")){
                        //加载jquery
                var script = document.createElement( "script" );
                        //设置属性
                        script.setAttribute('type', 'text/javascript');
                        script.setAttribute('media', "all");
                        script.setAttribute('charset', "utf-8");
                script.setAttribute('src', "/zftal-ui-v5-1.0.2/assets/js/other_jquery/jquery.min.js?ver=28814644");    
                // 先把js/css加到页面；如果script节点没有添加到DOM树中，在chrome和firefox中不会响应script的load事件    
            document.getElementsByTagName("head")[0].appendChild(script);
        }
        </script>
        <script type="text/javascript" src="/zftal-ui-v5-1.0.2/assets/js/jquery-migrate.min.js?ver=28814644"></script> 
</head>
<body>
<div class="error_v5">
        <div class="error_ico"><i class="error3"></i></div>
        <div class="error_con">
                <p class="error_title">无功能权限，</p>
                <p class="error_text2"><span class="time">5</span>秒后将自动关闭页面<a href="#" class="go_back0" onclick="closeWin();">立即关闭</a></p>
        </div>
</div>
<script type="text/javascript">

function lazyGo() {
        var sec = $(".error_text2 .time").text();
        $(".error_text2 .time").text(--sec);
        if (sec > 0){
                setTimeout("lazyGo();", 1000);
        }else{
                window.close();
        }
}

function closeWin(){
        window.close();
}

var times_1 = 0;
var intervalFunc = function(){
        if(jQuery){
                jQuery(function($) {
                        //计算高度
                        window.onresize = function(){
                                var body_height =       $(window).height();
                                var error_height=       $(".error_v5").height() + 50;
                                var margin_top  =       (body_height - error_height)/2;
                                var margin_top  =       (margin_top>0) ? margin_top : 0;
                                $(".error_v5").css("margin-top",margin_top);
                        }
                        $(window).resize();
                        setTimeout("lazyGo();", 1000);
                });
        }else{
                if(times_1 <= 10){
                        window.setTimeout(intervalFunc, 300);
                }
        }
        times_1 += 1;
};
window.setTimeout(intervalFunc,100);
</script>
</body>
</html>
: 13
{'code': 2333, 'msg': '请重试，若多次失败可能是系统错误维护或需更新接口'}

**Comment by Harrison3-1122** [comment]
请问一下您这个问题是如何解决的呀

**Comment by XinghaiGe** [comment]
我已经毕业了，账号登陆不了了。如果有需要你可以发我一个能登陆的账号，有时间帮你看看。2874903098@qq.com
